apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-api-deployment
  labels:
    app: portfolio-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-api
  template:
    metadata:
      labels:
        app: portfolio-api
    spec:
      containers:
        - name: portfolio-api-container
          image: portfolio-api
          imagePullPolicy: Never
          ports:
            - containerPort: 4000