version: "3.8"

services:
  portfolio-api:
    environment:
      - NODE_ENV=development
    container_name: portfolio-api-c
    image: portfolio-api-i
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    command: npm run start:dev
    volumes:
      - ./src:/app/src