apiVersion: v1
kind: Service
metadata:
  name: portfolio-api-service
spec:
  type: LoadBalancer
  selector:
    app: portfolio-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
